image: Ubuntu

environment:
  nodejs_version: "14"

test_script:
  - node --version
  - npm --version
  - npx @clobbr/cli run -u "https://60698fbde1c2a10017544a73.mockapi.io" --checks mean=200 median=200 stdDev=50 q5=150 q50=200 q95=250 q99=300 pctOfSuccess=95

build: off
